name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug", "help wanted"]
assignees:
  - CloakSelf
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. foobar#0000, xyz@foo.bar etc.
    validations:
      required: false
  - type: input
    id: gane
    attributes:
      label: Game
      description: What game was this script executed on
      placeholder: ex. Zombie Attack 
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what happened
      placeholder: Tell us what you see
    validations:
      required: true
  - type: dropdown
    id: exec
    attributes:
      label: What executor were you using?
      multiple: true
      options:
        - Synapse X
        - Scriptware
        - KRNL
        - Evon
        - Other
    validations:
      required: true
  - type: input
    id: other exec
    attributes:
      label: Executor
      description: If you answered Other to the previous question, please extend.
      placeholder: Vegas X
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
